install:
  - ps: >-
    write-output "installing sublime text 3"
    start-filedownload "http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203059%20x64.zip"
    write-output "installing Sublime%20Text%20Build%203059%20x64.zip"
    7z.exe x "Sublime%20Text%20Build%203059%20x64.zip" -o"C:\st" > $null
    mkdir "C:\st\Data\Packages" -force > $null
    mkdir "C:\st\Data\Packages\PowerShell" -force > $null
    cp -Recurse * "C:\st\Data\Packages\PowerShell" -Force
    git clone -q --branch=master https://github.com/my-personal-forks/UnitTesting.git "C:\st\Data\Packages\UnitTesting"
    write-output "installing pester"
    cinst pester

build: false

test_script:
  - ps: C:\st\Data\Packages\UnitTesting\sbin\run.ps1 "PowerShell"